on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: suilteam/cxy:latest-ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cxy package test --verbose
